### ISSUE TITLE
Question candidate expects 0 arguments, 1 provided

### ISSUE THREAD

**Issue by netbrain** [bytedeco/javacpp#370]
Im trying to create a opencv build off master with some custom flags, however im getting errors like this when trying to compile. What would be the cause of this? Im not to familiar with javacpp yet so i really dont know where to start fixing this issue.

But to me it looks like I either need to map a  CvBox2D() constructor with the float argument, or create the missing converter somewhere? What is your take on this?

```
/home/netbrain/dev/javacpp-presets/opencv/target/native/org/bytedeco/opencv/linux-x86_64-gpu/jniopencv_core.cpp:55942:118: error: no matching function for call to ‘CvBox2D::CvBox2D(jfloat&)’
In file included from /home/netbrain/dev/javacpp-presets/opencv/target/native/org/bytedeco/opencv/linux-x86_64-gpu/jniopencv_core.cpp:113:0:
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note: candidate: CvBox2D::CvBox2D()
 typedef struct CvBox2D
                ^~~~~~~
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note:   candidate expects 0 arguments, 1 provided
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note: candidate: constexpr CvBox2D::CvBox2D(const CvBox2D&)
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note:   no known conversion for argument 1 from ‘jfloat {aka float}’ to ‘const CvBox2D&’
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note: candidate: constexpr CvBox2D::CvBox2D(CvBox2D&&)
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note:   no known conversion for argument 1 from ‘jfloat {aka float}’ to ‘CvBox2D&&’
/home/netbrain/dev/javacpp-presets/opencv/target/native/org/bytedeco/opencv/linux-x86_64-gpu/jniopencv_core.cpp: In function ‘void Java_org_bytedeco_opencv_opencv_1core_CvBox2D_allocate__Ljava_nio_FloatBuffer_2Lorg_bytedeco_opencv_opencv_1core_CvSize2D32f_2F(JNIEnv*, jobject, jobject, jobject, jfloat)’:

```

**Comment by saudet** [comment]
Looks like some C++ compiler error. Make sure you're using the kind of compilers listed here:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by netbrain** [comment]
Yeah, it's not. Just tried compiling within the docker environment as described in Build-Environments. Any other tips?

**Comment by netbrain** [comment]
Are you sure this is not a mapping error? Been digging a bit further and when i look at the generated code i see the following:

```
JNIEXPORT void JNICALL Java_org_bytedeco_opencv_opencv_1core_CvBox2D_allocate__Lorg_bytedeco_opencv_opencv_1core_CvPoint2D32f_2Lorg_bytedeco_opencv_opencv_1core_CvSize2D32f_2F(JNIEnv* env, jobject obj, jobject arg0, jobject arg1, jfloat arg2) {
    CvPoint2D32f* ptr0 = arg0 == NULL ? NULL : (CvPoint2D32f*)jlong_to_ptr(env->GetLongField(arg0, JavaCPP_addressFID));
    jlong position0 = arg0 == NULL ? 0 : env->GetLongField(arg0, JavaCPP_positionFID);
    ptr0 += position0;
    CvSize2D32f* ptr1 = arg1 == NULL ? NULL : (CvSize2D32f*)jlong_to_ptr(env->GetLongField(arg1, JavaCPP_addressFID));
    jlong position1 = arg1 == NULL ? 0 : env->GetLongField(arg1, JavaCPP_positionFID);
    ptr1 += position1;
    jthrowable exc = NULL;
    try {
        CvBox2D* rptr = new CvBox2D(ptr0 == NULL ? CvPoint2D32f() : *ptr0, ptr1 == NULL ? CvSize2D32f() : *ptr1, arg2);
        jlong rcapacity = 1;
        JavaCPP_initPointer(env, obj, rptr, rcapacity, rptr, &JavaCPP_org_bytedeco_opencv_opencv_1core_CvBox2D_deallocate);
    } catch (...) {
        exc = JavaCPP_handleException(env, 7);
    }

    if (exc != NULL) {
        env->Throw(exc);
    }
}
```

and if i do the following changes...

```
        CvBox2D box = cvBox2D(ptr0 == NULL ? CvPoint2D32f() : *ptr0, ptr1 == NULL ? CvSize2D32f() : *ptr1, arg2);
        CvBox2D* rptr = &box
```

then the following error goes away:

```
/home/netbrain/dev/javacpp-presets/opencv/target/native/org/bytedeco/opencv/linux-x86_64-gpu/jniopencv_core.cpp: In function ‘void Java_org_bytedeco_opencv_opencv_1core_CvBox2D_allocate__Lorg_bytedeco_opencv_opencv_1core_CvPoint2D32f_2Lorg_bytedeco_opencv_opencv_1core_CvSize2D32f_2F(JNIEnv*, jobject, jobject, jobject, jfloat)’:
/home/netbrain/dev/javacpp-presets/opencv/target/native/org/bytedeco/opencv/linux-x86_64-gpu/jniopencv_core.cpp:55942:118: error: new initializer expression list treated as compound expression [-fpermissive]
         CvBox2D* rptr = new CvBox2D(ptr0 == NULL ? CvPoint2D32f() : *ptr0, ptr1 == NULL ? CvSize2D32f() : *ptr1, arg2);
                                                                                                                      ^
/home/netbrain/dev/javacpp-presets/opencv/target/native/org/bytedeco/opencv/linux-x86_64-gpu/jniopencv_core.cpp:55942:118: error: no matching function for call to ‘CvBox2D::CvBox2D(jfloat&)’
In file included from /home/netbrain/dev/javacpp-presets/opencv/target/native/org/bytedeco/opencv/linux-x86_64-gpu/jniopencv_core.cpp:113:0:
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note: candidate: CvBox2D::CvBox2D()
 typedef struct CvBox2D
                ^~~~~~~
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note:   candidate expects 0 arguments, 1 provided
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note: candidate: constexpr CvBox2D::CvBox2D(const CvBox2D&)
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note:   no known conversion for argument 1 from ‘jfloat {aka float}’ to ‘const CvBox2D&’
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note: candidate: constexpr CvBox2D::CvBox2D(CvBox2D&&)
/home/netbrain/dev/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/include/opencv2/core/types_c.h:1273:16: note:   no known conversion for argument 1 from ‘jfloat {aka float}’ to ‘CvBox2D&&’
/home/netbrain/dev/javacpp-presets/opencv/target/native/org/bytedeco/opencv/linux-x86_64-gpu/jniopencv_core.cpp: In function ‘void Java_org_bytedeco_opencv_opencv_1core_CvBox2D_allocate__Ljava_nio_FloatBuffer_2Lorg_bytedeco_opencv_opencv_1core_CvSize2D32f_2F(JNIEnv*, jobject, jobject, jobject, jfloat)’:
```

So to me it seems like i need to tell javacpp to create a slightly different code, but im unsure on how.

**Comment by saudet** [comment]
The code in the presets work fine. We don't need to change it.

**Comment by netbrain** [comment]
Yes, i know they work fine up to opencv 4.1.2, i'm however trying to make javacpp work with the current master release which has dnn with cuda support. however i'm now presented with these errors from the generated code from javacpp. 

I'm guessing that the issues i'm facing today will be present when the current master is released as a version.

**Comment by saudet** [comment]
I guess, but `CvBox2D` is part of the deprecated C API, so there's no reason why they would have modified that, but was it updated, and how? Can you check that?

**Comment by netbrain** [comment]
No, it wasn't updated. so, that is kind of puzzling . Now i'm trying to compile the 4.1.2 version with only the PR's that i'm interested in and see how that fares.

**Comment by netbrain** [comment]
Now i'm stuck with this:
```
/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-cuda4dnn-fast-yolov3/modules/imgproc/src/smooth.dispatch.cpp: In instantiation of 'bool cv::validateGaussianBlurKernel(std::vector<_RealType>&) [with T = cv::{anonymous}::ufixedpoint16]':
/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-cuda4dnn-fast-yolov3/modules/imgproc/src/smooth.dispatch.cpp:664:90:   required from here
/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-cuda4dnn-fast-yolov3/modules/imgproc/src/smooth.dispatch.cpp:593:24: error: conversion from '__gnu_cxx::__alloc_traits<std::allocator<cv::{anonymous}::ufixedpoint16> >::value_type {aka cv::{anonymous}::ufixedpoint16}' to 'double' is ambiguous
         validation_sum += softdouble((double)kernel[i]);
                        ^
/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-cuda4dnn-fast-yolov3/modules/imgproc/src/smooth.dispatch.cpp:593:24: note: candidates are:
In file included from /javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-cuda4dnn-fast-yolov3/modules/imgproc/src/smooth.dispatch.cpp:62:0:
/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-cuda4dnn-fast-yolov3/modules/imgproc/src/fixedpoint.inl.hpp:354:22: note: cv::{anonymous}::ufixedpoint16::operator int32_t() const
     CV_ALWAYS_INLINE operator int32_t() const { return saturate_cast<int32_t>(); }
                      ^
/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-cuda4dnn-fast-yolov3/modules/imgproc/src/fixedpoint.inl.hpp:353:22: note: cv::{anonymous}::ufixedpoint16::operator int16_t() const
     CV_ALWAYS_INLINE operator int16_t() const { return saturate_cast<int16_t>(); }
                      ^
/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-cuda4dnn-fast-yolov3/modules/imgproc/src/fixedpoint.inl.hpp:352:22: note: cv::{anonymous}::ufixedpoint16::operator uint16_t() const
     CV_ALWAYS_INLINE operator uint16_t() const { return saturate_cast<uint16_t>(); }
                      ^
/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-cuda4dnn-fast-yolov3/modules/imgproc/src/fixedpoint.inl.hpp:351:22: note: cv::{anonymous}::ufixedpoint16::operator int8_t() const
     CV_ALWAYS_INLINE operator int8_t() const { return saturate_cast<int8_t>(); }
                      ^
/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-cuda4dnn-fast-yolov3/modules/imgproc/src/fixedpoint.inl.hpp:350:22: note: cv::{anonymous}::ufixedpoint16::operator uint8_t() const
     CV_ALWAYS_INLINE operator uint8_t() const { return saturate_cast<uint8_t>(); }
                      ^
make[2]: *** [modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/smooth.dispatch.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/imgproc/CMakeFiles/opencv_imgproc.dir/all] Error 2
make: *** [all] Error 2

```

All of these CV_ALWAYS_INLINE operator... I see that the opencv.patch file contains a few of those where they are simply commented out, would that be the fix for this aswell? And why am I getting this compilation issue anyway? Is it due to the compiler javacpp is using?

**Comment by saudet** [comment]
I think that means it needs those definitions that are commented out in the patch. IIRC, these functions didn't work with GCC 4.8 for some reason, but we can use GCC 7 and 8 on CentOS now so that shouldn't be an issue anymore.

**Comment by netbrain** [comment]
Yeah tried upgrading to GCC 8, but got the exact same errors. I must be missing something...

**Comment by netbrain** [comment]
does it have anything to do with the following settings maybe?
CC="gcc -m32" CXX="g++ -std=c++11 -m32"

**Comment by netbrain** [comment]
Ok, went back to basics, compiled opencv manually, not through javacpp-preset/opencv, and it works fine, no issues whatsoever. Then tried to compile with the opencv preset and it fails on several compilation errors. I then commented out all patches except a cmake patch that enables compilation within the same directory (or something like that). This also works fine except that it doesn't find libopencv_java.so at the end. So.. anyways, this leaves me to believe that one or more patches is causing the issue i'm facing.  Am now running a compilation attempt where i removed all the patches that targets source code file, but leaving cmake changes intact.

**Comment by netbrain** [comment]
Now im left with the following:

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /javacpp-presets/opencv/src/gen/java/org/bytedeco/opencv/opencv_quality/QualityMSE.java:[35,26] method does not override or implement a method from a supertype
[ERROR] /javacpp-presets/opencv/src/gen/java/org/bytedeco/opencv/opencv_quality/QualityMSE.java:[36,26] method does not override or implement a method from a supertype
[ERROR] /javacpp-presets/opencv/src/gen/java/org/bytedeco/opencv/opencv_quality/QualityMSE.java:[37,26] method does not override or implement a method from a supertype
[INFO] 3 errors

```

This surely has to be a mapping issue or?

**Comment by saudet** [comment]
No, it's a bug in that module, but there a patch for that. Make sure you're applying it.

**Comment by netbrain** [comment]
/javacpp-presets/opencv/target/native/org/bytedeco/opencv/linux-x86_64-gpu/jniopencv_cudacodec.cpp:2655:64: error: 'Stream' has not been declared
         bool rval = (bool)ptr->nextFrame(*ptr0, ptr1 == NULL ? Stream::Null() : *ptr1);

**Comment by netbrain** [comment]
Core/cuda.hpp contains the stream definition, but is not included by the generated code for cudacodec.hpp. So how do i add the definition to the mapping?

**Comment by saudet** [comment]
It's already perfectly included. There's nothing else that we should need to do:
https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/main/java/org/bytedeco/opencv/presets/opencv_cudacodec.java

**Comment by netbrain** [comment]
Im just trying to understand why it's not working in my case. Heres a snippet of the generated code.

`
cv::cuda::Stream* ptr1 = arg1 == NULL ? NULL : (cv::cuda::Stream*)jlong_to_ptr(env->GetLongField(arg1, JavaCPP_addressFID));
    jlong position1 = arg1 == NULL ? 0 : env->GetLongField(arg1, JavaCPP_positionFID);
    ptr1 += position1;
    jboolean rarg = 0;
    jthrowable exc = NULL;
    try {
        bool rval = (bool)ptr->nextFrame(*ptr0, ptr1 == NULL ? Stream::Null() : *ptr1);
        rarg = (jboolean)rval;
    } catch (...) {
`

as you can see ptr1 is instianciated with the cv::cuda:: namespace prefix, however in the shorthand if sentence it is not. Why is that? What causes this? And how do i enforce Stream:Null() to actually get prefixed with cv::cuda:: ?

**Comment by saudet** [comment]
We'll have to check the differences with the master branch where this doesn't happen and narrow down the cause that way.

**Comment by netbrain** [comment]
So there is no way to define that Stream should be prefixed with cv::cuda? Alternatively, can i disable cudacodec?

**Comment by saudet** [comment]
Sure, just delete `opencv_cudacodec.java`.

**Comment by saudet** [comment]
I've fixed the bug causing problems with `opencv_cudacodec` in the last commit.

For the original issue, the problem is that they've now disabled constructors by default for the C API to fix issue https://github.com/bytedeco/javacv/issues/1129, so we also have to skip over them with JavaCPP with something like this:
```java
infoMap.put(new Info("defined(CV__ENABLE_C_API_CTORS) && defined(__cplusplus) && !defined(__CUDACC__)",
                     "defined(CV__ENABLE_C_API_CTORS) && defined(__cplusplus)").define(false))
```

**Comment by saudet** [comment]
Bug fix is in just released version 1.5.3. Thanks for reporting and for testing all this!
