### ISSUE TITLE
Crash on Android 2.3

### ISSUE THREAD

**Issue by Pitel** [bytedeco/javacpp#47]
After upgrading to 1.1, our app crashes on Android 2.3.

```
FATAL EXCEPTION: Thread-17
java.lang.NoClassDefFoundError: org.bytedeco.javacpp.Pointer
    at java.lang.Runtime.nativeLoad(Native Method)
    at java.lang.Runtime.nativeLoad(Native Method)
    at java.lang.Runtime.loadLibrary(Runtime.java:432)
    at java.lang.System.loadLibrary(System.java:554)
    at cz.master.annie.audio.LolAudio.init(LolAudio.java:202)
    at cz.master.annie.app.init.GlobalInitializerThread.run(GlobalInitializerThread.java:24)
 Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.Pointer
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:234)
    at org.bytedeco.javacpp.Loader.putMemberOffset(Loader.java:693)
    at java.lang.Runtime.nativeLoad(Native Method) 
    at java.lang.Runtime.nativeLoad(Native Method) 
    at java.lang.Runtime.loadLibrary(Runtime.java:432) 
    at java.lang.System.loadLibrary(System.java:554) 
    at cz.master.annie.audio.LolAudio.init(LolAudio.java:202) 
    at cz.master.annie.app.init.GlobalInitializerThread.run(GlobalInitializerThread.java:24) 
 Caused by: java.lang.NoClassDefFoundError: org.bytedeco.javacpp.Pointer
    at java.lang.Class.classForName(Native Method) 
    at java.lang.Class.forName(Class.java:234) 
    at org.bytedeco.javacpp.Loader.putMemberOffset(Loader.java:693) 
    at java.lang.Runtime.nativeLoad(Native Method) 
    at java.lang.Runtime.nativeLoad(Native Method) 
    at java.lang.Runtime.loadLibrary(Runtime.java:432) 
    at java.lang.System.loadLibrary(System.java:554) 
    at cz.master.annie.audio.LolAudio.init(LolAudio.java:202) 
    at cz.master.annie.app.init.GlobalInitializerThread.run(GlobalInitializerThread.java:24) 
 Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.Pointer in loader dalvik.system.PathClassLoader[/data/app/cz.master.annie-1.apk]
    at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:240)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:551)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.Class.classForName(Native Method) 
    at java.lang.Class.forName(Class.java:234) 
    at org.bytedeco.javacpp.Loader.putMemberOffset(Loader.java:693) 
    at java.lang.Runtime.nativeLoad(Native Method) 
    at java.lang.Runtime.nativeLoad(Native Method) 
    at java.lang.Runtime.loadLibrary(Runtime.java:432) 
    at java.lang.System.loadLibrary(System.java:554) 
    at cz.master.annie.audio.LolAudio.init(LolAudio.java:202) 
    at cz.master.annie.app.init.GlobalInitializerThread.run(GlobalInitializerThread.java:24) 
```

It works fine on devices with 4.x and newer.

Also, ProGuard config:
```
-dontwarn org.bytedeco.javacpp.tools.BuildMojo
-dontwarn org.apache.maven.plugin.logging.Log
-dontwarn org.slf4j.**
-keep class org.bytedeco.javacpp.** { *; }
-keep class cz.master.annie.audio.javacpp.** { *; } # Without this, it doesn't work on Nexus S
```

**Comment by saudet** [comment]
Yes, it's no longer compatible with Android 4.0:
http://bytedeco.org/news/2015/10/25/moving-to-java-se-7/
If you still need support for Android 2.3, building a custom `javacpp.jar` without `AutoCloseable` should work.
